### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by MaxJoas** [jan-forest/autoencodix_package#4]
### Collection of high-level ToDo's 
- [x] Add Unit Tests
- [x] Add GitHub Actions CI/CD pipeline
- [x] Discuss input data
- [ ] Show Jan how to contribute
- [ ] Discuss discussion issues
- [ ] Plan who is contributing what next
- [ ] Discuss/Decide which new architectures to implement
